### PR TITLE
Order archived configurations dates by desc

### LINKED ISSUE #342: Reorder the version date in the configuration History
**Describe the bug**
when we want to list the latest versions of a configuration, the previous ones are listed in ascending orders.
The oldest one is so presented first ... 
As the listed is maxed to (maybe) 50 occurences, the latest version is not accessible

**To Reproduce**
Go to this configuration for example
https://studio.tailer.ai/data-workflows/tables-to-tables/configurations/000040_load_bda_crm_PROD
Click on the datetime under the name of the last user who updated the conf (on the right upper corner)
And see the list

**Expected behavior**
They should be listed in descending modification datetime order 

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: mac
 - Browser Chrome
 - Version Version 91.0.4472.114 (Build officiel) (x86_64)

### PR DESCRIPTION
**Pull request by Eronne**
## Related issue(s)

Closes #342

## Description

This PR is ordering archived configurations by descending dates.

## What does this PR do?

- [x] Update dates order

## Deploy notes

Review & merge.

### CODE REVIEW

**Comment by OlivierColin** [comment]
Hello @Eronne 

je viens de checker sur l'appli en preview, OK pour moi.
Dis moi comment je valide via Github stp ...

**Review by OlivierColin — APPROVED** [review]
OK pour moi.

**Comment by romone22** [comment]
Hello, it's working well. But is it possible to add the update_by information next to the update_date in the listing ? It could help to find the right version of a previous configuration

**Comment by romone22** [comment]
Moreover, when a configuration is activated / desactivated /activated by a user from the studio web front, the user email is not displayed but his user_id. 
image

Is it possible to fix it in this PR or in a new one ?

**Comment by Eronne** [comment]
I will add the `updated_by` property & for the email instead of the user id, it is the next issue planned in ZenHub => https://github.com/Tailer-Platform/tailer-studio/issues/285

**Comment by romone22** [comment]
Ok, so for the moment, we let the update like that, without the update-by and the fix on the user_id.
OK to deploy in production

**Pull request merged**
