### PR TITLE
Improve activities overview

### LINKED ISSUE #347: Aggregate Activities Overview page
Cette feature consiste à présenter la même vue que Activities Overview Runs mais agrégée aux niveau Job et au niveau Conf.
On va donc ajouter deux onglets de type listing à droite de l'onglet Runs

Dans les deux cas, nous utilisons exactement le même dataset que pour les Runs (on ne refait donc pas de requête Firestone, on ne fera que agréger les données sur deux dimensions que sont les Jobs est les Configurations

# Agrégation au niveau Job
Sur le même Dataset que les Runs, on va agréger les données sur les dimensions suivantes :
	⁃	Environnement
	⁃	Conf Type
	⁃	Conf Id -> (avec un lien vers la configuration source)
	⁃	Trigger

Puis on va agréger les évènements selon les règles suivantes :
	⁃	Nb Exécutions = Nb de Runs Id distincts agrégés sur les 4 dimensions précédentes
	⁃	Last Status = Status du dernier run trié par date d'exécution descendante
	⁃	Last Duration = Durée de la dernière exécution
	⁃	Nb Success = Nb Runs en succès
	⁃	Nb Failed = Nb Runs en Failed

# Agrégation au niveau Conf
Sur le même Dataset que les Runs, on va agréger les données sur les dimensions suivantes :
	⁃	Environnement
	⁃	Conf Type
	⁃	Conf Id -> (avec un lien vers la configuration source)

Puis on va agréger les évènements selon les règles suivantes :
	⁃	Nb Exécutions = Nb de Runs Id distincts agrégés sur les 4 dimensions précédentes
	⁃	Nb Jobs Distincts = Nb de Job ID distincts (il sera different de 1 que pour les STS et STT)
	⁃	Last Status = Status du dernier run trié par date d'exécution descendante
	⁃	Last Duration = Durée de la dernière exécution
	⁃	Nb Success = Nb Runs en succès
	⁃	Nb Failed = Nb Runs en Failed

### PR DESCRIPTION
**Pull request by Eronne**
## Related issue(s)

Closes #347

## Description

This PR improves `activities-overview`.

## What does this PR do?

- [x] Remove unused `activities-overview` configurations
- [x] Job view
- [x] Conf view

## Deploy notes

Review & merge.

### CODE REVIEW

**Comment by romone22** [comment]
image

**Comment by romone22** [comment]
image

**Comment by romone22** [comment]
image

**Comment by Eronne** [comment]
@romone22 for the number of line modification, the default number is 10 or do you want to update it to 50 for example ?

**Comment by romone22** [comment]
@Eronne Let stay the default number to 10. 

It’s not necessary to persiste this value. It could generate mistakes like show 500 items  from a simple list and moving to a heavy listing where 500 items will generate long query difficult to display

**Comment by Eronne** [comment]
Do I remove also the `documentation` tab on others data operations?

**Comment by Eronne** [comment]
@romone22 also this default value set to 50 will be set for all listing tables.

**Comment by romone22** [comment]
Bugs to fix:

- [ ] In the Runs listing, for a Tables-to-Tables execution, clicking on the execution date time to see the Run Details failed.
- [ ] In the Jobs listing, we should apply the rules above to get the right runs when clicking on the # Excutions Links
> If the Job is a STS, STT, TTT, TTS, and VM_LAUNCHER, and the status is **not** "NO_MATCH", we should use the full job-id of the last run in the search box of the Runs listing
> if the Job is a STS or a STT and the status is "NO_MATCH", we should use the conf_id of the job in the search box of the Runs listing
- [ ] In the Conf listing, we should apply the rules above to get the right runs when clicking on the # **Jobs** Links
> We should use the conf_id, in the Jobs search box as is it. 

In fact, we can't have a perfect filter because the job_id are not well structured for all the conf type and runs. We should improve that with @julienguarino

**Comment by Eronne** [comment]
> If the Job is a STS, STT, TTT, TTS, and VM_LAUNCHER, and the status is not "NO_MATCH", we should use the full job-id of the last run in the search box of the Runs listing

And what if the status is `NO_MATCH` ?

**Comment by romone22** [comment]
Here the rules to apply to switch from the Confs/Jobs Tab to the Jobs/Runs tab.

### For STT / STS Configuration type

**-> if the job_id of the last run is not null (possible when Last Status = NO_MATCH)**

from Confs Tab to Jobs Tab
and from Confs to Runs Tab

The pattern to search in the jobs/runs tab is based on the job_id of the last conf execution.
To make the pattern, we should extract the trigger placeholder of the job_id 
example : 
- job_id : storage-to-tables|000010|mirror-fd-io-exc-jules-n-in-input|PROD|{{FD_DATE}}-{{FD_TIME}}-jules-visiteurs-magasins.csv
- trigger (last part of the job_id separated by "|") : {{FD_DATE}}-{{FD_TIME}}-jules-visiteurs-magasins.csv
- Patern to search in the Jobs/Runs Tab : storage-to-tables|000010|mirror-fd-io-exc-jules-n-in-input|PROD

from Jobs Tab to Runs Tab
The pattern to search in the runs tab is the full job_id of the last job execution

**-> If the job_id is null,** 

Confs -> Jobs
Confs -> Runs
Jobs -> Runs

The pattern to search in the runs/jobs tab is the conf_id of the last execution


### for TTT / TTS / VM Launcher configuration type
Confs -> Jobs
Confs -> Runs
Jobs -> Runs

The pattern to search in the runs/jobs tab is the conf_id of the last execution


### Other Issues

The conf type filter is not synchronized between the different tabs

The link for on the Last Execution Date on the Confs tab for the tables-to-tables are still not working whereas they are ok on the Runs and Jobs tab for the same tables-to-tables conf


ON the api-to-storage  , add links on the "Last Execution" value to the "Run Detailed view"  and add link on the "conf ID" value to the "Conf Detailed view" of this execution.

**Comment by romone22** [comment]
In the conf listing, if the trigger is "NOT_MATCH", the filter aply for Jobs and Runs is "NOT_SET". 
We should change that and agg the configuration ID of the NOT_MATCH conf in the search filter

image

**Comment by romone22** [comment]
Test Ok

**Pull request merged**
